export type ZendeskUser<UserFields = any> = {
  id: number;
  url: string;
  name: string;
  email: string | null;
  created_at: string;
  updated_at: string;
  time_zone: string;
  iana_time_zone: string;
  phone: string | null;
  shared_phone_number: string | null;
  photo: string | null;
  locale_id: number;
  locale: string;
  organization_id: number | null;
  role: string;
  verified: boolean;
  external_id: string;
  tags: string[];
  alias: string | null;
  active: boolean;
  shared: boolean;
  shared_agent: boolean;
  last_login_at: string | null;
  two_factor_auth_enabled: boolean | null;
  signature: string | null;
  details: string | null;
  notes: string | null;
  role_type: string | null;
  custom_role_id: number | null;
  moderator: boolean;
  ticket_restriction: string;
  only_private_comments: boolean;
  restricted_agent: boolean;
  suspended: boolean;
  default_group_id: number | null;
  report_csv: boolean;
  user_fields: UserFields
};
